Use correct logging method
Fixes an issue introduced with 2af8284493c4631b5584da4a976d1e8534cba9b8
where suddenly errors like these appeard in my systemd log:

```
gnome-shell[5070]: JS ERROR: Exception in callback for signal: icon: TypeError: Util.Logger.fatal is not a function
_getIconInfo@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:408:21
_cacheOrCreateIconByName@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:334:27
_updateIcon@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:513:27
_emit@resource:///org/gnome/gjs/modules/signals.js:135:27
_onPropertiesChanged/<@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:17
_onPropertiesChanged@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:208:9
refreshPropertyOnProxy/<@/home/takuto/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:42:37
```

I also changed the log level to debug because this is not critical and only noisy
logging IMHO. Critical / fatal errors should lead to program
termination which is not the case here.