appIndicator: Fix runtime error when icon can not be loaded
[why]
With commit
  bac3f1c0 appIndicator: Support fixed-size icons

a bug has been introduced, that is triggered if an icon can not be
loaded:

gnome-shell[17071]: JS ERROR: TypeError: Util.Logger.fatal is not a function

[how]
Our util.js has indeed no fatal(), but only these:
    debug(message)
    warn(message)
    error(message)
    critical(message)

So I reckon critical() is what has been meant.

Signed-off-by: Fini Jastrow <ulf.fini.jastrow@desy.de>